### ISSUE TITLE
question: are index.js and registerServiceWorker.js used in any way or can they be safely deleted?

### ISSUE THREAD

**Issue by wintermute42** [diabelb/create-react-app-typescript-redux#1]
question: are index.js and registerServiceWorker.js used in any way or can they be safely deleted, while keeping the respective ts files?

**Comment by diabelb** [comment]
Hello ;)

These files can be safety deleted. It's my mistake. They should not be in the repository. I'll fix it in next release.

**Comment by wintermute42** [comment]
Ok, thanks for the info.
